# Generated by Django 2.0.13 on 2019-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='id',
            new_name='ID',
        ),
        migrations.AddField(
            model_name='place',
            name='GPSX',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='GPSY',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='NAME',
            field=models.CharField(default='', max_length=50),
        ),
    ]
