# Generated by Django 2.0.13 on 2019-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190905_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='CONTENT_DEPTH',
            field=models.IntegerField(default=0),
        ),
    ]
